### PR TITLE
[WIP] Attach lxc containers to lxcbr0 by configuring a new network_mode parameter

### PR DESCRIPTION
**Pull request by towe75**
A new driver parameter "network_mode" switches the behavior of the containers network interface.
The default value "bridge",  will attach the container to the standard "lxcbr0" bridge. A value of "host" will instead share the network with the host, like it was in previous versions.

It's also possible to set the "network_mode" parameter within the task driver config. It simply overrides the global driver parameter and thus allows a different mode for specific containers.

### CODE REVIEW

**Comment by tgross** [comment]
Sounds good on that, @towe75. Looks like there's a merge conflict now that the other PR has been merged.

**Comment by towe75** [comment]
@tgross merge conflict is solved.
I changed the PR title to reflect that i want to give the code another iteration before merging. At least the bridge name should be configurable, a test would also be nice.

**Comment by dinesh** [comment]
@tgross can we merge this PR and have a release for lxc driver? I'm using `lxc` based containers and need non-host networking.

**Comment by towe75** [comment]
@dinesh, @tgross  sorry for not continuing here. I wanted to make the bridge name configurable but the PR can be useful even with hardcoded "lxcbr0" because it's the defacto default bridge name on debian'ish systems.

**Comment by tgross** [comment]
Ok, we're going to merge this as-is and cut a new tag for it.

**Comment by tgross** [comment]
Tagged as https://github.com/hashicorp/nomad-driver-lxc/releases/tag/v0.2.0

**Pull request merged**
